-- Suggested Supabase schema for the Travel Wallet demo.
-- This keeps wallet cash counts and daily expenses in separate tables,
-- which makes it easy to query totals and group by date.

create extension if not exists pgcrypto;

create table if not exists public.wallet_denominations (
  id bigint generated by default as identity primary key,
  denomination integer not null unique,
  count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  amount integer not null check (amount >= 0),
  expense_date date not null,
  memo text,
  created_at timestamptz not null default now()
);

create index if not exists expenses_expense_date_idx
  on public.expenses (expense_date desc);

create or replace view public.daily_expense_totals as
select
  expense_date,
  count(*) as item_count,
  sum(amount)::bigint as total_amount
from public.expenses
group by expense_date
order by expense_date desc;

alter table public.wallet_denominations enable row level security;
alter table public.expenses enable row level security;

-- This demo uses the Supabase service role key from Vercel serverless functions.
-- No public RLS policy is required unless you later expose the database directly to the browser.
